### ISSUE TITLE
Response status code: 503

### ISSUE THREAD

**Issue by aoGFX** [RyuzakiH/Temp-Mail-API#2]
HttpRequestException: Response status code does not indicate success: 503 (Service Temporarily Unavailable).

any help ?

**Comment by RyuzakiH** [comment]
Website just used cloudflare, I'll try to update it today.

**Comment by RyuzakiH** [comment]
Bypassed Cloudflare protection in [version 1.1.3](https://www.nuget.org/packages/TempMail.API/1.1.3) .

**Comment by antonioalopezfernandez** [comment]
Still happening, any ideas?

**Comment by RyuzakiH** [comment]
I tested it and it works good for me.
The problem that made that exception is the website uses cloudflare which uses two types of challenges.
One is javascript challenge and the other one is reCaptcha so the problem happens if it's a captcha or your IP is banned, the javascipt one can be solved easily.
I use this library [CloudflareSolver](https://www.nuget.org/packages/CloudflareSolver) to bypass cloudflare, it provides the fail reason if any of the two previous problems happen.
It provides solving the captcha challenge if you provided a [2Captcha](http://2captcha.com) key (it's not free).
I'll throw a descriptive exception telling if it needs 2captcha key or your IP is banned if there's a problem.
If the problem is your IP so you should change it.
I'll add the new exception to make it more clearer (my bad) today.
Until I update it try it using another IP to see if this is the problem.

**Comment by RyuzakiH** [comment]
Added 2Captcha in [version 1.1.4](https://www.nuget.org/packages/TempMail.API/1.1.4).
Try it, and tell me if there's any problem.

**Comment by antonioalopezfernandez** [comment]
I'll do ASAP.

Thank you very much!

**Comment by antonioalopezfernandez** [comment]
Hi,

I'm afraid there is a different error now:

> Cloudflare.CloudflareException: Cloudflare (JS): response cookie not found
>    en TempMail.API.Client.StartNewSession()

The code:
```
        static void Main(string[] args)
        {
            if (Environment.Is64BitOperatingSystem)
            {
                PrepararEntornoWin64();

                var client = new Client();
                client.StartNewSession();

                Console.WriteLine(client.Email);
            }
        }
```

I've tried this and previous version from two different IP's.

**Comment by RyuzakiH** [comment]
It's an exception related to CloudflareSolver library, but it doesn't happen with me so I can't debug it, so I'll need your help.


Have you tried opening the site in browser just to make sure it's not an IP problem.
Then tell me if the response contains the below text or not (having captcha for example):

> Checking your browser before accessing temp-mail.org.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…

Another way is:
Try using Hotspot Shield (it ran successfully for me).

Try these and keep me updated.
I hope we can solve it.

**Comment by antonioalopezfernandez** [comment]
Response contains that text, it lasts 5 seconds to get to my mail account. However, I'd prefer not to use a VPN (i'm trying to get some stuff working for everyone, not just for us).

Thank you in advance.

**Comment by RyuzakiH** [comment]
Since it's a [CloudflareSolver](https://www.nuget.org/packages/CloudflareSolver) problem, so I think it's [Jint](https://github.com/sebastienros/jint) (Javascript engine that parses the JS challenge and solve it).
I'm saying Jint as this library only depends on 3 libraries:

- [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json)
it can't be it I think.
- [2CaptchaAPI](https://www.nuget.org/packages/2CaptchaAPI)
you don't use a 2captcha api key.
- [Jint](https://www.nuget.org/packages/Jint)
maybe Jint interprets JS differently on different machines.

I'm just thinking with you, what about your OS?

**Comment by RyuzakiH** [comment]
If you have some time, can you use fiddler and run your code again.
Only 3 requests are issued, the first two are what we need.

1. GET request to [temp-mail](https://temp-mail.org/) returns 503 Service Temporarily Unavailable
2. GET request to https://temp-mail.org/cdn-cgi/l/chk_jschl?s=S&jschl_vc=JSCHL_VC&pass=PASS&jschl_answer=JSCHL_ANSWER returns 302 Moved Temporarily
with the 4 capitalized words replaced with other values.

I need you to send me the responses of the previous two requests (response heades and body).
I'll run them on my machine and compare to identify which part is leading to that error.
